version: "3.9"
services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "8012:80"
  backend:
    build: ./backend
    restart: always
    ports:
      - "8011:8000"
    volumes:
      - /var/log/slu/:/logs/
    depends_on:
      - frontend