version: "3.9"
services:
  frontend:
    build: ./frontend
    restart: always
  backend:
    build: ./backend
    restart: always
    environment:
      - MONGO_URI
    volumes:
      - /var/log/slu/:/var/log/slu/
    depends_on:
      - frontend