FROM rust:bullseye as builder

WORKDIR /usr/src/app
COPY . .
RUN cargo build --release

FROM debian:bullseye
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/target/release/backend /usr/local/bin/app
EXPOSE 8000

ENV ROCKET_PORT=8000
ENV RUST_BACKTRACE=1

CMD ["app"]
